# Generated by Django 4.0.4 on 2022-04-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
