# Generated by Django 4.0.4 on 2022-04-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comments_votes_posts_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='votes',
        ),
        migrations.AddField(
            model_name='posts',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='like', to='app.posts'),
        ),
    ]
