# Generated by Django 4.0.4 on 2022-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_posts_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='like', to='app.posts'),
        ),
    ]
