# Generated by Django 4.0.4 on 2022-04-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='app/images/default-user.jpg', upload_to=''),
        ),
    ]
