# Generated by Django 4.0.4 on 2022-04-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_conversation_conversationmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessages',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessages',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='conversationmessages',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessages',
        ),
    ]
