# Generated by Django 4.0.4 on 2022-04-30 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_conversationmessages_conversation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='app.message')),
            ],
        ),
    ]
